### ISSUE TITLE
Deko3D not working with Yuzu

### ISSUE THREAD

**Issue by Sausty** [devkitPro/deko3d#8]
I'm interested in switching from OpenGL to Deko3D.

I've made a test project with the exact same shaders, code and directory setup as the deko_basic example. Yet, when i start up the game it just shows a black screen. I'm using the default settings of Yuzu. Is the problem coming from Yuzu or Deko3D?

**Comment by fincs** [comment]
The platform targetted by deko3d (and libnx/etc) is the Nintendo Switch. Emulators are not the target platform. deko3d and all associated code (such as the examples) has been developed and verified to work on real hardware. If a given piece of code works on hardware but not on an emulator, then it should be reported to the emulator devs so that they can fix it. It would be a good idea if you could also test your code on hardware, too.

**Comment by ReinUsesLisp** [comment]
I'm kind of late, deko_basic renders using Clear. The macro used for that is currently broken on yuzu's MME JIT. You can disable it going into Configure > Debug > Disable macro JIT.

Like fincs said, report these issues on yuzu's github or ping me (@Rodrigo) on Discord.

**Comment by Sausty** [comment]
Just tested it out, worked perfectly 
The holy solution coming from the sky
Thank you so much Rein, have a great day :)
